#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 4
bspc config normal_border_color "#3b4252"
bspc config focused_border_color "#4C566A"
bspc config urgent_border_color "#BF616A"
bspc config presel_border_color "#81a1c1"

SPACES=$(bspc query -D)
for SPACE in $SPACES; do
  bspc config -d ${SPACE} window_gap 12
  bspc config -d ${SPACE} top_padding 0
  bspc config -d ${SPACE} bottom_padding 0
  bspc config -d ${SPACE} left_padding 0
  bspc config -d ${SPACE} right_padding 0
done

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc config automatic_scheme dwindle
bspc config split_ratio 0.50
bspc config auto_alternate true
bspc config auto_cancel true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle true
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
pgrep -x sxhkd >/dev/null || sxhkd &
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bscp rule -a polybar manage=off
bspc rule -a Screenkey manage=off

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &
nitrogen --restore &
numlockx on &
flameshot &
picom -b &
dunst &
